<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<UserSecretsId>262e2c2a-d2a9-4b12-a631-4c9bb2a5ff78</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventManager.Application\EventManager.Application.csproj" />
    <ProjectReference Include="..\EventManager.Domain\EventManager.Domain.csproj" />
    <ProjectReference Include="..\EventManager.Infrastructure\EventManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  <PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
