<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<UserSecretsId>0ca5f154-4198-41a2-8fa4-2e34ea45e126</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Web\Common.Web.csproj" />
    <ProjectReference Include="..\EventMicroService.Application\EventMicroService.Application.csproj" />
    <ProjectReference Include="..\EventMicroService.Domain\EventMicroService.Domain.csproj" />
    <ProjectReference Include="..\EventMicroService.Infrastructure\EventMicroService.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.18.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.18.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.18.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
	</ItemGroup>

</Project>
