<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<UserSecretsId>ca4d1a92-53f7-4fdb-95e5-859d2d5d92c0</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BookingMicroService.Application\BookingMicroService.Application.csproj" />
		<ProjectReference Include="..\BookingMicroService.Domain\BookingMicroService.Domain.csproj" />
		<ProjectReference Include="..\BookingMicroService.Infrastructure\BookingMicroService.Infrastructure.csproj" />
		<ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

</Project>
